In [23]:
import pandas as pd
from datetime import datetime
import numpy

In [2]:
df_weather = pd.read_csv("/Users/ziyingwang/Documents/UCD/Summer/tmp/data/weather.csv")

In [3]:
df_weather.head(6)

dt                         dt_iso  timezone        city_name  \
0  1483228800  2017-01-01 00:00:00 +0000 UTC         0  Custom location   
1  1483232400  2017-01-01 01:00:00 +0000 UTC         0  Custom location   
2  1483236000  2017-01-01 02:00:00 +0000 UTC         0  Custom location   
3  1483239600  2017-01-01 03:00:00 +0000 UTC         0  Custom location   
4  1483243200  2017-01-01 04:00:00 +0000 UTC         0  Custom location   
5  1483246800  2017-01-01 05:00:00 +0000 UTC         0  Custom location   

         lat       lon  temp  visibility  dew_point  feels_like  ...  \
0  53.345035 -6.267261  5.39      9999.0       4.35        1.78  ...   
1  53.345035 -6.267261  5.39      9999.0       4.35        2.28  ...   
2  53.345035 -6.267261  5.39      9999.0       4.35        2.28  ...   
3  53.345035 -6.267261  4.39      9999.0       3.36        0.04  ...   
4  53.345035 -6.267261  4.39      9999.0       2.42        0.04  ...   
5  53.345035 -6.267261  3.39      9999.0       1.44       -1.23  ...   

   wind_gust  rain_1h  rain_3h  snow_1h  snow_3h  clouds_all  weather_id  \
0        NaN     2.30      NaN      NaN      NaN          75         501   
1        NaN     1.51      NaN      NaN      NaN          75         501   
2        NaN     0.64      NaN      NaN      NaN          75         500   
3        NaN     0.17      NaN      NaN      NaN          75         500   
4        NaN      NaN      NaN      NaN      NaN          75         803   
5        NaN      NaN      NaN      NaN      NaN          40         802   

   weather_main  weather_description  weather_icon  
0          Rain        moderate rain           10n  
1          Rain        moderate rain           10n  
2          Rain           light rain           10n  
3          Rain           light rain           10n  
4        Clouds        broken clouds           04n  
5        Clouds     scattered clouds           03n  

[6 rows x 28 columns]

In [4]:
# print the number of rows and features
num_rows = df_weather.shape[0]
features = df_weather.shape[1]
print(f"The dataset has {num_rows} rows with {features} features.")

The dataset has 27186 rows with 28 features.


In [5]:
# print the last 5 rows of the dataset
print("The last 5 Rows are:")
df_weather.tail(5)

The last 5 Rows are:


dt                         dt_iso  timezone        city_name  \
27181  1577818800  2019-12-31 19:00:00 +0000 UTC         0  Custom location   
27182  1577822400  2019-12-31 20:00:00 +0000 UTC         0  Custom location   
27183  1577826000  2019-12-31 21:00:00 +0000 UTC         0  Custom location   
27184  1577829600  2019-12-31 22:00:00 +0000 UTC         0  Custom location   
27185  1577833200  2019-12-31 23:00:00 +0000 UTC         0  Custom location   

             lat       lon  temp  visibility  dew_point  feels_like  ...  \
27181  53.345035 -6.267261  9.33      9999.0       6.42        9.33  ...   
27182  53.345035 -6.267261  8.81      9999.0       6.09        7.02  ...   
27183  53.345035 -6.267261  7.86      9999.0       5.33        7.86  ...   
27184  53.345035 -6.267261  7.49      9999.0       4.09        7.49  ...   
27185  53.345035 -6.267261  7.21      9999.0       4.52        5.85  ...   

       wind_gust  rain_1h  rain_3h  snow_1h  snow_3h  clouds_all  weather_id  \
27181       2.68      NaN      NaN      NaN      NaN          75         803   
27182        NaN      NaN      NaN      NaN      NaN          90         804   
27183       1.79      NaN      NaN      NaN      NaN          90         804   
27184       1.79      NaN      NaN      NaN      NaN          75         803   
27185        NaN      NaN      NaN      NaN      NaN          75         803   

       weather_main  weather_description  weather_icon  
27181        Clouds        broken clouds           04n  
27182        Clouds      overcast clouds           04n  
27183        Clouds      overcast clouds           04n  
27184        Clouds        broken clouds           04n  
27185        Clouds        broken clouds           04n  

[5 rows x 28 columns]

In [6]:
# print the data type for each feature
df_weather.dtypes

dt                       int64
dt_iso                  object
timezone                 int64
city_name               object
lat                    float64
lon                    float64
temp                   float64
visibility             float64
dew_point              float64
feels_like             float64
temp_min               float64
temp_max               float64
pressure                 int64
sea_level              float64
grnd_level             float64
humidity                 int64
wind_speed             float64
wind_deg                 int64
wind_gust              float64
rain_1h                float64
rain_3h                float64
snow_1h                float64
snow_3h                float64
clouds_all               int64
weather_id               int64
weather_main            object
weather_description     object
weather_icon            object
dtype: object

- dt is a timestamp, I will leave this as a integer and use it to create the features `date` and `time`.
- dt_iso is the datetime in iso format as a string, this will be obsolete when I create the `date` and `time` features. We do not need the data in 2017 and 2019 and will drop them.
- As our estimation is based in Dublin so we dont need the timezone, cityname and lat. I will drop them.
- Only keep tmp as our main temperature indicator.
- Sea_level and grnd_level are not indicative enough. I will drop them. 
- we dont need weather_icon and will drop them later.

In [7]:
# convert 'dt' from timestamp to datetime
df_weather['dt'] = pd.to_datetime(df_weather['dt'], unit='s')

In [16]:
# drop features
useless_features = ['visibility', 'dew_point', 'wind_deg', 'wind_gust'
]

df_weather = df_weather.drop(columns=useless_features)

In [17]:
df_weather.dtypes

dt                     datetime64[ns]
temp                          float64
pressure                        int64
humidity                        int64
wind_speed                    float64
rain_1h                       float64
rain_3h                       float64
snow_1h                       float64
snow_3h                       float64
clouds_all                      int64
weather_id                      int64
weather_main                   object
weather_description            object
dtype: object

In [20]:
df_weather_2018=df_weather.loc[(df_weather["dt"]>'2017-12-31 23:00:00')&(df_weather["dt"]<'2019-1-1 00:00:00')]

In [21]:
df_weather

dt  temp  pressure  humidity  wind_speed  rain_1h  \
0     2017-01-01 00:00:00  5.39      1019        93        5.10     2.30   
1     2017-01-01 01:00:00  5.39      1019        93        4.10     1.51   
2     2017-01-01 02:00:00  5.39      1019        93        4.10     0.64   
3     2017-01-01 03:00:00  4.39      1019        93        6.20     0.17   
4     2017-01-01 04:00:00  4.39      1019        87        6.20      NaN   
...                   ...   ...       ...       ...         ...      ...   
27181 2019-12-31 19:00:00  9.33      1030        82        0.45      NaN   
27182 2019-12-31 20:00:00  8.81      1030        83        3.10      NaN   
27183 2019-12-31 21:00:00  7.86      1030        84        0.45      NaN   
27184 2019-12-31 22:00:00  7.49      1029        79        0.45      NaN   
27185 2019-12-31 23:00:00  7.21      1029        83        2.10      NaN   

       rain_3h  snow_1h  snow_3h  clouds_all  weather_id weather_main  \
0          NaN      NaN      NaN          75         501         Rain   
1          NaN      NaN      NaN          75         501         Rain   
2          NaN      NaN      NaN          75         500         Rain   
3          NaN      NaN      NaN          75         500         Rain   
4          NaN      NaN      NaN          75         803       Clouds   
...        ...      ...      ...         ...         ...          ...   
27181      NaN      NaN      NaN          75         803       Clouds   
27182      NaN      NaN      NaN          90         804       Clouds   
27183      NaN      NaN      NaN          90         804       Clouds   
27184      NaN      NaN      NaN          75         803       Clouds   
27185      NaN      NaN      NaN          75         803       Clouds   

      weather_description  
0           moderate rain  
1           moderate rain  
2              light rain  
3              light rain  
4           broken clouds  
...                   ...  
27181       broken clouds  
27182     overcast clouds  
27183     overcast clouds  
27184       broken clouds  
27185       broken clouds  

[27186 rows x 13 columns]

In [30]:
df_weather['temp'].unique()

array([ 5.39,  4.39,  3.39, ...,  3.15,  1.81, 12.96])

In [31]:
df_weather['wind_speed'].unique()

array([ 5.1 ,  4.1 ,  6.2 ,  5.7 ,  6.7 ,  7.7 ,  8.2 ,  9.3 ,  3.6 ,
        3.1 ,  4.6 ,  7.2 ,  2.1 ,  2.6 ,  1.  ,  1.5 ,  0.  ,  0.5 ,
        6.  ,  9.8 , 10.8 ,  8.8 , 10.3 , 11.3 , 13.4 , 14.4 , 13.9 ,
       12.4 , 12.9 , 11.8 , 15.4 , 14.9 , 16.5 ,  2.  ,  8.  ,  9.  ,
       10.  , 11.  , 17.  , 21.6 , 22.1 , 20.1 , 14.  ,  5.  ,  7.  ,
        3.  ,  4.12,  4.63,  2.57, 16.  , 18.  , 18.5 , 17.5 ,  4.  ,
        1.54,  6.17,  5.66,  5.14,  8.23,  8.75,  6.69,  2.06,  9.77,
        9.26,  3.09,  1.03,  4.25,  7.72,  4.53,  4.43,  4.46,  4.62,
        4.45,  4.37,  4.56,  4.79,  4.66,  4.74,  4.67,  4.69,  4.76,
        6.07,  5.74,  1.34,  2.68,  2.24,  3.13,  3.58,  1.79,  4.02,
        4.92,  5.81,  0.89,  0.45,  5.36,  4.47,  6.26,  7.6 ,  0.51,
        7.15,  6.71])

In [32]:
df_weather['rain_1h'].unique()

array([ 2.3 ,  1.51,  0.64,  0.17,   nan,  0.11,  0.26,  0.39,  0.49,
        0.53,  0.31,  1.44,  1.87,  1.18,  0.74,  0.7 ,  0.18,  0.12,
        0.41,  0.22,  0.84,  0.23,  0.25,  0.21,  0.89,  0.47,  0.14,
        0.13,  0.16,  0.15,  0.28,  0.4 ,  0.97,  1.89,  2.41,  2.7 ,
        1.69,  0.44,  0.27,  0.37,  0.1 ,  0.34,  0.3 ,  0.32,  0.51,
        1.54,  0.82,  0.35,  0.62,  0.81,  0.68,  0.52,  0.71,  1.23,
        0.24,  0.38,  0.5 ,  1.02,  1.13,  0.61,  0.33,  0.19,  0.2 ,
        0.29,  0.63,  0.8 ,  0.36,  1.29,  0.99,  0.69,  0.55,  0.72,
        0.96,  0.79,  1.17,  1.21,  0.48,  0.54,  0.73,  0.66,  0.46,
        0.65,  0.77,  1.52,  2.16,  1.99,  0.43,  1.78,  0.6 ,  1.04,
        1.08,  0.9 ,  0.94,  2.09,  1.14,  0.42,  0.57,  0.76,  1.12,
        0.91,  1.31,  1.47,  1.74,  2.07,  1.95,  0.83,  1.05,  0.59,
        1.62,  0.45,  0.98,  0.87,  0.58,  1.16,  1.27,  1.  ,  0.93,
        1.06,  1.25,  1.34,  2.13,  2.69,  2.66,  1.77,  0.75,  1.2 ,
        1.58,  1.9 ,

In [33]:
df_weather['rain_3h'].unique()

array([nan])

In [34]:
df_weather['snow_1h'].unique()

array([ nan, 0.18, 0.45, 0.53, 0.52, 0.46, 0.26, 0.11, 0.19, 0.34, 0.77,
       0.16, 0.64, 0.55, 0.1 , 0.13, 0.21, 0.14, 0.15, 0.12, 0.31, 0.43,
       0.17, 0.23, 0.39, 0.67, 0.93, 1.08, 1.17, 1.29, 1.24, 1.1 , 0.98,
       0.54, 0.63, 0.5 , 0.4 , 0.75, 0.86, 0.82, 0.79, 0.56, 0.51, 0.27,
       0.2 , 0.25, 0.35, 0.33, 0.28, 1.52])

In [35]:
df_weather['snow_3h'].unique()

array([nan])

In [37]:
duplicate_and_none_value_features = ['rain_3h', 'snow_1h', 'snow_3h']
df_weather = df_weather.drop(columns= duplicate_and_none_value_features)

In [39]:
df_weather.dtypes

dt                     datetime64[ns]
temp                          float64
pressure                        int64
humidity                        int64
wind_speed                    float64
rain_1h                       float64
clouds_all                      int64
weather_id                      int64
weather_main                   object
weather_description            object
dtype: object